#!/usr/bin/env python

"""
This script will print out all existing apps with their Apple ID and bundle name.
"""
from __future__ import print_function
import pytunesconnect as pytunes

if __name__ == "__main__":

	app_list = pytunes.list_apps()

	for app in app_list:
		print(app['adamId'] + ': ' + app['name'])